matrix:
  include:
    - name: "Linux Test"
      language: node_js
      node_js: "12.13.0"
      os: linux
      if: NOT commit_message =~ /^:hammer:/
      dist: xenial
      sudo: false
      install:
        - cd test
        - npm ci
    - name: "OSX Test"
      os: osx
      if: NOT commit_message =~ /^:hammer:/
      language: node_js
      node_js: "12.13.0"
      install:
        - cd test
        - npm ci
    - name: "Linux Build"
      os: linux
      dist: xenial
      sudo: false
      if: commit_message =~ /^:hammer:/
      env:
        - ISBUILD=true
        - SYSNAME=Linux
      install:
        - chmod +x src/unpack.sh && src/unpack.sh
      script:
        - chmod +x src/linux-labsound.sh && src/linux-labsound.sh
    - name: "OSX Build"
      os: osx
      if: commit_message =~ /^:hammer:/
      language: cpp
      compiler: clang++
      env:
        - ISBUILD=true
        - SYSNAME=OSX
      install:
        - chmod +x src/unpack.sh && src/unpack.sh
      script:
        - chmod +x src/osx-labsound.sh && src/osx-labsound.sh


deploy:
  on:
    all_branches: true
    condition: $ISBUILD = true
  provider: releases
  name: "Binary for $SYSNAME"
  body: $TRAVIS_COMMIT_MESSAGE
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  overwrite: true
  draft: true
  prerelease: false
  tag_name: "$SYSNAME"
  file_glob: true
  file: src/LabSound-master/dist/*
