name: Build Binaries
defaults:
  run:
    shell: bash

on:
  workflow_dispatch

jobs:
  create_release:
    name: Create Release
    if: contains('["raub"]', github.actor)
    runs-on: ubuntu-latest

    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}

    steps:

      - name: Fetch Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
          cache: 'npm'

      - name: Get Package Version
        id: package-version
        run: node -p "'version='+require('./package').version" >> $GITHUB_OUTPUT

      - name: Create Draft Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          tag_name: ${{ steps.package-version.outputs.version }}
          name: Release ${{ steps.package-version.outputs.version }}
          body: Binaries at ${{ github.sha }}

  build:
    name: Build
    strategy:
        matrix:
          os: [ubuntu-20.04, windows-2022, macos-11, [self-hosted, linux, ARM64]]

    runs-on: ${{ matrix.os }}

    steps:

      - name: Fetch Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
          cache: 'npm'

      - name: Install Modules
        run: npm ci --ignore-scripts

      - name: Add msbuild to PATH
        if: matrix.os == 'windows-2022'
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64

      - name: Build Linux
        if: matrix.os != 'windows-2022' && matrix.os != 'macos-11'
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq xorg-dev
          chmod +x src/linux.sh && src/linux.sh
      - name: Store Binaries
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          tag_name: linux-${{ github.run }}-${{ github.sha }}
          name: LabSound Linux
          body: Linux LabSound binaries at ${{ github.sha }}
          files: src/build/*

      - name: Build Windows
        if: matrix.os == 'windows-2022'
        shell: cmd
        run: |
          src\windows.cmd
      - name: Store Binaries
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          tag_name: windows-${{ github.run }}-${{ github.sha }}
          name: LabSound Windows
          body: Windows LabSound binaries at ${{ github.sha }}
          files: src/build/*

      - name: Build OSX
        if: matrix.os == 'macos-11'
        run: |
          chmod +x src/osx.sh && src/osx.sh
      - name: Store Binaries
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          tag_name: osx-${{ github.run }}-${{ github.sha }}
          name: LabSound OSX
          body: OSX LabSound binaries at ${{ github.sha }}
          files: src/build/*

      - name: Get Package Version
        id: package-version
        shell: bash
        run: node -p "'version='+require('./package').version" >> $GITHUB_OUTPUT

      - name: Pack Files
        id: pack-files
        run: node -e "require('addon-tools-raub').actionPack()" >> $GITHUB_OUTPUT

      - name: Store Binaries
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          tag_name: ${{ steps.package-version.outputs.version }}
          name: Release ${{ steps.package-version.outputs.version }}
          files: ${{ steps.pack-files.outputs.pack }}
