name: Build OSX GLFW

on:
  workflow_dispatch

jobs:
  Build:
    if: contains('["raub"]', github.actor)
    runs-on: macos-10.15

    steps:

      - name: Fetch Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.16.0

      - name: Build
        run: |
          chmod +x src/osx-glfw.sh && src/osx-glfw.sh
      - name: Store Binaries
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          tag_name: osx-glfw-${{ github.run }}-${{ github.sha }}
          name: GLFW OSX
          body: OSX GLFW binaries at ${{ github.sha }}
          files: src/build/*
