name: Build Linux LabSound

on:
  workflow_dispatch

jobs:
  Build:
    if: contains('["raub"]', github.actor)
    runs-on: ubuntu-16.04

    steps:

      - name: Fetch Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.16.0

      - name: Build
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq xorg-dev
          chmod +x src/linux-glfw.sh && src/linux-glfw.sh
      - name: Store Binaries
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          tag_name: linux-glfw-${{ github.run }}-${{ github.sha }}
          name: LabSound Linux
          body: Linux LabSound binaries at ${{ github.sha }}
          files: src/build/*
