name: ESLint
defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-20.04

    steps:

      - name: Fetch Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
          cache: 'npm'

      - name: Install Modules
        run: npm ci --ignore-scripts

      - name: Run ESLint
        run: npm run eslint
